name: slowrotenv
channels:
  - conda-forge
dependencies:
  - python=3.9.20
  - markupsafe=3.0.2
  - matplotlib=3.9.4
  - mda-xdrlib=0.2.0
  - mdanalysis=2.7.0
  - mdanalysistests=2.7.0
  - mdtraj=1.10.1
  - numpy=1.23.5
  - openff-amber-ff-ports=0.0.4
  - openff-forcefields=2024.09.0
  - openff-interchange=0.3.24
  - openff-interchange-base=0.3.24
  - openff-models=0.1.2
  - openff-toolkit=0.16.5
  - openff-toolkit-base=0.16.5
  - openff-units=0.2.2
  - openff-utilities=0.1.12
  - openmm=8.2.0
  - openssl=3.5.2
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parmed=4.3.0
  - pdbfixer=1.10
  - pymbar=4.0.3
  - pymbar-core=4.0.3
  - rdkit=2024.03.5
  - scikit-learn=1.5.2
  - scipy=1.13.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - smirnoff99frosst=1.1.0
  - soupsieve=2.5
  - sqlalchemy=2.0.36
  - yaml=0.2.5
  - pip
  - pip:
      - alabaster==0.7.16
      - amberutils==21.0
      - babel==2.17.0
      - docutils==0.21.2
      - edgembar==0.2
      - imagesize==1.4.1
      - markdown-it-py==3.0.0
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - mmpbsa-py==16.0
      - myst-parser==3.0.1
      - packmol-memgen==2024.2.9
      - pdb4amber==22.0
      - pockets==0.9.1
      - pymsmt==22.0
      - pytraj==2.0.6

